### ISSUE TITLE
Collect HP laptop specs

### ISSUE THREAD

**Issue by PialKanti** [DreamersWorld/WebCMP#1]
https://ryanscomputers.com/notebook/all-notebook/filter/cat/148.html

**Comment by manashmandal** [comment]
Done, check [crawler branch](https://github.com/DreamersWorld/WebCMP/tree/crawlers)

**Comment by manashmandal** [comment]
Download and rename the file to `.csv`
[hp_specs.txt](https://github.com/DreamersWorld/WebCMP/files/720988/hp_specs.txt)

**Comment by PialKanti** [comment]
Collect price

**Comment by manashmandal** [comment]
Fixed. rename the extension as `.csv`
[hp_spec_price - Copy.txt](https://github.com/DreamersWorld/WebCMP/files/721471/hp_spec_price.-.Copy.txt)
